// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsgr28RWuPj4MzbO23LpayEYg1wYSJkqs',
    appId: '1:899142789545:web:10330bc6ef016066e2fcb8',
    messagingSenderId: '899142789545',
    projectId: 'iot-smart-home-81abd',
    authDomain: 'iot-smart-home-81abd.firebaseapp.com',
    databaseURL: 'https://iot-smart-home-81abd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-81abd.firebasestorage.app',
    measurementId: 'G-EK6PH9WV94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9XmqzwgmPxvhSWDcxya4J92oQ5WVvzM',
    appId: '1:899142789545:android:90fe6c7eae91296ae2fcb8',
    messagingSenderId: '899142789545',
    projectId: 'iot-smart-home-81abd',
    databaseURL: 'https://iot-smart-home-81abd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-81abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8jSYW6gGMvgEsYhdP39SjVUJFwbAHAc',
    appId: '1:899142789545:ios:2d3fcf81c112eb73e2fcb8',
    messagingSenderId: '899142789545',
    projectId: 'iot-smart-home-81abd',
    databaseURL: 'https://iot-smart-home-81abd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-81abd.firebasestorage.app',
    iosBundleId: 'IoT.Smart.Home.iot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8jSYW6gGMvgEsYhdP39SjVUJFwbAHAc',
    appId: '1:899142789545:ios:2d3fcf81c112eb73e2fcb8',
    messagingSenderId: '899142789545',
    projectId: 'iot-smart-home-81abd',
    databaseURL: 'https://iot-smart-home-81abd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-81abd.firebasestorage.app',
    iosBundleId: 'IoT.Smart.Home.iot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsgr28RWuPj4MzbO23LpayEYg1wYSJkqs',
    appId: '1:899142789545:web:1a64f8250e9f4f6de2fcb8',
    messagingSenderId: '899142789545',
    projectId: 'iot-smart-home-81abd',
    authDomain: 'iot-smart-home-81abd.firebaseapp.com',
    databaseURL: 'https://iot-smart-home-81abd-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'iot-smart-home-81abd.firebasestorage.app',
    measurementId: 'G-MHD4RH6GV4',
  );

}